### ISSUE TITLE
'Trainer' object has no attribute 'writer'

### ISSUE THREAD

**Issue by zhang-21** [yanconglin/Deep-Hough-Transform-Line-Priors#11]
Hi Dr Lin, thanks for your great work.
When I'm trying to train the module using the pre-processed dataset from LCNN accroding to your instruction:

`python ./train.py -d 0 --identifier baseline config/wireframe.yaml`

and the terminal output:
![1](https://user-images.githubusercontent.com/41133467/172345158-054292ab-ffd8-492d-b7b5-f5d7986f6275.png)

The code I used is the original version without modification, thererfore, I don't understand it.

Looking forward to your reply!

**Comment by yanconglin** [comment]
Em, no idea. I did multiple tests several times when releasing the code.   No idea why this happens. I will have a look later. the 'writer' function is only to record loss values.

**Comment by zhang-21** [comment]
Thanks for your reply. I guess some of my dependences in the vitual env are conflict to each other. Could you please give me a certain list of dependences (such as requirements.txt)?

Thanks for your help : )

**Comment by yanconglin** [comment]
em. unfortunately, I am not able to do this. The original repo no longer exists on the local cluster.  I do not think it is a depedency problem, as self.writer is missing. Try to uncomment line43-46,  from [here](https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/ad4e742c6d34612aa01b95da36ab325dbe62eb99/ht-lcnn/lcnn/trainer.py#L43)  to  [there](https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/ad4e742c6d34612aa01b95da36ab325dbe62eb99/ht-lcnn/lcnn/trainer.py#L46).

**Comment by zhang-21** [comment]
Really thanks for your help, and I have solved this problem.
