### ISSUE TITLE
What is the vote_index?

### ISSUE THREAD

**Issue by toshi2k2** [yanconglin/Deep-Hough-Transform-Line-Priors#13]
Hi, Can you explain what the vote_index variable is? I couldn't find any comments in the code explaining it.

**Comment by yanconglin** [comment]
vote_index is a tensor that records the bins that a pixel votes for.  It is of size Rows*Cols*Height*Width, where Rows and Cols are the image size, and Height and Width indicate the size of the output HT feature map (or the number of offsets and angles). HT is done by matrix multiplication, i.e.  [Batch * Channel,  Rows * Cols]  @ [Rows * Cols,  Height * Width] = Batch*Channel*Height*Width.

**Comment by HassanBinHaroon** [comment]
Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
