### ISSUE TITLE
How to test the given pretrained model?

### ISSUE THREAD

**Issue by zhang-21** [yanconglin/Deep-Hough-Transform-Line-Priors#14]
Hi Dr Lin,
    Following the introduction, I tried to evaluate the performance of the given pretrained model. However, when using
`python ./process.py config/wireframe.yaml model/checkpoint.pth.tar data/wireframe`
the terminal shows:
![1](https://user-images.githubusercontent.com/41133467/188675976-7c1b86a6-9763-40de-b6be-ab47c3598295.jpg)
The pretrained model(tar file) is located in /ht-lcnn/model.
The dataset I used is the processed one downloaded from the given link. 
Could you please give me some advices?

Thanks!

**Comment by yanconglin** [comment]
Em. let me think about this, since it has been such a long time. can you please try testing on gpus - adding "-d 0 "

**Comment by zhang-21** [comment]
It doesn't work for me.
Well, the traning code(train.py) and demo code(demo.py) can run normally, therefore, I think the installation has correctly done.
I don't understand the parameter `logs/pretrained-model/npz/000312000` becase there aren't any files in the log folder.

**Comment by yanconglin** [comment]
yes, seems you are right. There is indeed a problem.  Fixed now `/process.py config/wireframe.yaml <path-to-checkpoint.pth>`.  thank you for the bug report.
