### ISSUE TITLE
Unable to reproduce results

### ISSUE THREAD

**Issue by kirill-ivanov-a** [yanconglin/Deep-Hough-Transform-Line-Priors#15]
Hi, @yanconglin!

Thank you for the awesome line detector!

Unfortunately, I cannot reproduce your sAP score on the Wireframe dataset using your pre-trained model. I only received **43.30**. Is everything okay with the model?

### Environment
Google Colab: 
- OS: Ubuntu 18.04
- Python 3.7.15
- torch 1.12.1+cu113
- CUDA Version: 11.2

### How to reproduce
I followed your instructions in [README.md](https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/master/README.md)
```
./process.py config/wireframe.yaml <path-to-checkpoint.pth>
```

**Comment by yanconglin** [comment]
em, that is strange. Neither I nor anyone else using this repo has ever reported this issue.  unfortunately, I can verify at this moment, since the original data no longer exists...

**Comment by kirill-ivanov-a** [comment]
Okay, I solved it. The problem was the same as [here](https://github.com/cherubicXN/hawp/issues/31). Division semantics changed in new versions of python

**Comment by yanconglin** [comment]
Thank you for the update.
