### ISSUE TITLE
Request: Changing the hypermeter in wireframe.yaml

### ISSUE THREAD

**Issue by faisalshahbaz** [yanconglin/Deep-Hough-Transform-Line-Priors#16]
Hi @yanconglin 

I'd like to train the model to overfit our custom dataset, which consists of 5000 frames. These images have dimensions of 640 pixels in width, 360 pixels in height, and 3 color channels.

What modifications should I make to the 'wireframe.yaml' configuration file to achieve this goal of overfitting the model on our dataset?

**Comment by yanconglin** [comment]
hi faisalshahbaz,
Sorry for the late reply. 
It has been a long time. The details already slip my mind. You probably need to try and test several times.
I briefly went through the code. It seems you also need to change [this line](
https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/2ce70ca2ade3e300f63769326f46f8d55b642ebf/ht-lcnn/train.py#L118)  to "vote_index = hough_transform(rows=90, cols=160, theta_res=3, rho_res=1)"  as images will be downsampled x4.
