### ISSUE TITLE
About saving the vote_index.mat

### ISSUE THREAD

**Issue by Billy-ZTB** [yanconglin/Deep-Hough-Transform-Line-Priors#18]
Hello! I noticed that before training the network, I should generate a vote_index.mat. However, when I tried to generate and save the vote index for a 256*256 image, there came up an error:
`ht_map = hough_transform(256, 256, 3, 1)`
`vote_index = ht_map.astype(np.float32)`
`sio.savemat('vote_index256.mat', {'vote_index': ht_map})`
OverflowError: Python int too large to convert to C long
![image](https://github.com/user-attachments/assets/2dd4bfda-bb9b-44d2-9663-7bdb209c9724)
It seems that the matrix is too big to restore. Is there any way to restore this matrix efficiently? 
By the way, if I want to use hough transform in each decoder stage of my network to get multiscale line features, should I generate multiple "vote_index"s for every resolution?

Looking forward to your kind reply!

**Comment by yanconglin** [comment]
Please take a look at this project, where a CUDA implementation is available for high-resolution HT. 
It has been tested on 256x256 feature maps.
Links:
https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/7292b2e0a458770072d69e9c08d651a5edac9a27/parameterization.py#L78

https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/7292b2e0a458770072d69e9c08d651a5edac9a27/vpd/models/vanishing_net.py#L24

**Comment by Billy-ZTB** [comment]
> Please take a look at this project, where a CUDA implementation is available for high-resolution HT. It has been tested on 256x256 feature maps. Links: https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/7292b2e0a458770072d69e9c08d651a5edac9a27/parameterization.py#L78
> 
> https://github.com/yanconglin/VanishingPoint_HoughTransform_GaussianSphere/blob/7292b2e0a458770072d69e9c08d651a5edac9a27/vpd/models/vanishing_net.py#L24

Wow, thank you for your rapid reply! I will take a look at this project and modify my code. Thank you again!

**Comment by Billy-ZTB** [comment]
Adding a hough transform layer same as the VanishingPoint_HoughTransform_GaussianSphere repository causes a huge computation burden. I added a HT_CONV layer to make ht and iht transformation on an 8 * 64 * 256 * 256 tensor in my network, the training time cost of one epoch increases from 18min to 35min, is it caused by the huge matrices multiplication? Are there any efficient implementations?

**Comment by yanconglin** [comment]
Resolution increased x4 times. it will definitely lead to longer latency. So far I do not see other options. Perhaps downscaling the feature maps would the the first thing to try, although I do know exactly what you try to achieve.

**Comment by Billy-ZTB** [comment]
Thank you! I will try it later.



---- Replied Message ----
| From | ***@***.***> |
| Date | 11/18/2024 16:01 |
| To | ***@***.***> |
| Cc | Zhang ***@***.***>***@***.***> |
| Subject | Re: [yanconglin/Deep-Hough-Transform-Line-Priors] About saving the vote_index.mat (Issue #18) |

Resolution increased x4 times. it will definitely lead to longer latency. So far I do not see other options. Perhaps downscaling the feature maps would the the first thing to try, although I do know exactly what you try to achieve.

**Comment by yanconglin** [comment]
In case you need high-resolution HT, it is better to optimize the CUDA code using shared memory stuff. It will perhaps solve your problem. My implementation is a minimal, workable version.

**Comment by Billy-ZTB** [comment]
I was using the CUDA implementation of ht and iht in VanishingPoint_HoughTransform_GaussianSphere, I think maybe I should use the hough transform in a deeper stage which has lower resolution. Thank you for your suggestion!
