### ISSUE TITLE
backbone multi-task parameters

### ISSUE THREAD

**Issue by hichem-abdellali** [yanconglin/Deep-Hough-Transform-Line-Priors#2]
Hi,

Could you please add more details about the backbone multi-task parameters and what is there meaning for the network in the `wireframe.yaml` , also what does means to define the num_classes to be 5 (sum of head_size )? 

the thing is that I don't understand the motivation behind this `head_size` and what does it represent
Thanks

**Comment by yanconglin** [comment]
HI,  djidan,

You can find thd details here: 
https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/812d8c21e98e7b11b2e81b88faad8c8709cbd364/ht-lcnn/lcnn/models/multitask_learner.py#L60-L62

Two channels for the junction map, two channels for the offset, and one channel for the line map.

**Comment by hichem-abdellali** [comment]
Hi again, 

May I ask you please what do you mean by the offset, is it referring to the Junction center location loss in the paper ? 

Thank in advance

**Comment by yanconglin** [comment]
` joff = output[offset[1] : offset[2]].reshape(n_jtyp, 2, batch, row, col) `

joff: given a point is at (510,500) in the original image (512x512), after downsampling to 128x128, its location is at (127.5, 125). joff (the displacement/offset/shift to the junction point) is  (0.5, 0) in this case.

**Comment by HassanBinHaroon** [comment]
Take a look at the following repository too. 

https://github.com/HassanBinHaroon/deep-hough-transform
