### ISSUE TITLE
Can't Unzip/Untar the pretrained model downloaded from SURFdrive

### ISSUE THREAD

**Issue by omrastogi** [yanconglin/Deep-Hough-Transform-Line-Priors#5]
Trying to untar using ~tar -xvf checkpoint.pth.tar
The errors says:
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors

On window this is the error:
![WhatsApp Image 2021-09-21 at 10 52 46 AM](https://user-images.githubusercontent.com/43903014/134118953-057774b9-ac00-4ed8-bb35-481ccd9fe036.jpeg)

**Comment by yanconglin** [comment]
Do not unzip the checkpoint. Download directly and use it as it is.

**Comment by omrastogi** [comment]
It worked! Thank you
