### ISSUE TITLE
Format of training label

### ISSUE THREAD

**Issue by omrastogi** [yanconglin/Deep-Hough-Transform-Line-Priors#6]
Hi Yancong, Its needless to say what a incredible job you are doing. 

I am trying to write a data loader to train the model. Can you give some idea about format of label data. 
How can I train my custom dataset? (The datasets for this project is unfortunately not available)

I would like to know, essential information needed to train the model. Specifically I don't understand the following:- 

![Screenshot from 2021-09-23 13-16-36](https://user-images.githubusercontent.com/43903014/134471537-3a9c1944-f066-4c00-9b1c-f71a448c02f4.png)

See, if you can help me. 
Thank you in advance.

**Comment by omrastogi** [comment]
Here is what I already understand: 
The structure of the dataset is as follows: 
data/wireframe 
--> train(folder) ----> label for train image in '.npz' format
--> valid(folder) ----> label for validation image in '.npz' format
--> images with same name as their label counterparts in train/valid folder, having an extension of ".png"

**Comment by yanconglin** [comment]
hi, Omrastogi,

Thank you for the interest.
Please check this: https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/bbe6b8f533e81070cb2880600901a38eeb58cc9d/ht-lcnn/dataset/wireframe.py
You will find all the details about the data format. 
The best practice would be:  (1) download the dataset, and run the script (mentioned above) by yourself.  

Yancong

**Comment by yanconglin** [comment]
Feel free to re-open if you have further questions.
