### ISSUE TITLE
How to take reference to a particular Hough Line?

### ISSUE THREAD

**Issue by PIjarihd** [yanconglin/Deep-Hough-Transform-Line-Priors#7]
I have used Hough LIne transform. Out of many lines detected, I want to take a particualr line. How should I take that?
P.S. there are many similar images. The images are different in size and angle(rotation).

**Comment by yanconglin** [comment]
Hi, afraid I do not fully understand your question.  Since you know which line to pick,  why not pick it up from the predictions.  The line here is a line (w/o endpoints) or a line segment?  Or you want to track the line in the HT space? can you pls elaborate (better with some some pics).
BTW, happy new year of 2022!

**Comment by PIjarihd** [comment]
![image_rot_](https://user-images.githubusercontent.com/90297273/147992805-64ffdaf8-ed3c-4257-8070-e2395b8de025.PNG)
The right side picture in the above image is the original image. The card picture is rotated upto some degree. I have many card images and they can be of any rotation. The yellow arrow shows the line I want to take reference. The left side shows the hough transform. I want to take a reference to the line pointed by yellow arrow. How can I do that? Any idea. My ultimate goal is to rotate the image straight so that the line which I have mentioed comes parralle with x-axis.

**Comment by yanconglin** [comment]
Honestly, I do not see why you get those red lines after HT.  It seems there is always a line of interest (the yellow arrow). If this is the case,  there is awalys a bin with a stronger response in the HT space that corresponds to the line of interest. Find the column index (thetats) and then calculate the amount of rectification you need (e.g. the difference to theta=0/90).  Then the problems becomes how to find this line. It is very likely there is some noise which might impact this hand-crafted process.  Given the information you shared, I can only think about this naive approach.  Remind me of a recent paper [It's About Time: Analog Clock Reading in the Wild](https://arxiv.org/abs/2111.09162) where the task is to align a clock and then read its time.  Hopefully this might be useful or interesting to you.
