### ISSUE TITLE
How to resume to train ?

### ISSUE THREAD

**Issue by Muyulinlinlin** [yanconglin/Deep-Hough-Transform-Line-Priors#8]
I would like to ask what instructions should be executed on the command line to continue after suspending the training model?

**Comment by yanconglin** [comment]
Can you clarify a bit:  resume from a checkpoint?   If this is the case, add path to the checkpoint_latest.pth.tar [here](https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/ad4e742c6d34612aa01b95da36ab325dbe62eb99/ht-lcnn/config/wireframe.yaml#L6). Then you can continue training from the previous/latest checkpoint.

**Comment by Muyulinlinlin** [comment]
> Can you clarify a bit: resume from a checkpoint? If this is the case, add path to the checkpoint_latest.pth.tar [here](https://github.com/yanconglin/Deep-Hough-Transform-Line-Priors/blob/ad4e742c6d34612aa01b95da36ab325dbe62eb99/ht-lcnn/config/wireframe.yaml#L6). Then you can continue training from the previous/latest checkpoint.

Thank you so much !
