### ISSUE TITLE
About the file of  _vecl_a.jpg

### ISSUE THREAD

**Issue by Muyulinlinlin** [yanconglin/Deep-Hough-Transform-Line-Priors#9]
Hello, Dr.Lin,
I have a question about whether the image file with the suffix __vecl_a.jpg_ generated after Testing Pretrained Models is the detection result of two-dimensional lines,
The reason I'm asking this question is because he only has red lines.

**Comment by yanconglin** [comment]
sorry, I do not follow your question. Can you pls show me some pictures or elaborate? It has been a long time...
